name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build with Buildozer
      uses: artem-ryabov/buildozer-action@v1
      with:
        work-dir: .
        buildozer-version: stable
